name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: api
    - name: List Dependencies
      run: dotnet list package > dependencies.txt
      working-directory: api
    - name: Collect Dependencies
      uses: actions/upload-artifact@v2
      with:
        name: Dependencies
        path: api/dependencies.txt      
    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity normal --output ./_build
      working-directory: api
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: api
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: HressAPI
        path: "./api/_build"   
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Publish Artifacts to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ez-stapp-hressorg
        package: "./api/_build"
        slot-name: production  
